-- ClimaFlow - Etapa 02
-- Execute no SQL Editor do Supabase.

create table if not exists public.favoritos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nome_item text not null unique,
  dados_extra jsonb
);

alter table public.favoritos enable row level security;

-- O projeto da disciplina não usa login, por isso a aplicação pública usa o papel anon.
revoke all on table public.favoritos from anon;
grant select, insert, delete on table public.favoritos to anon;
grant usage, select on sequence public.favoritos_id_seq to anon;

drop policy if exists "favoritos_select_anon" on public.favoritos;
drop policy if exists "favoritos_insert_anon" on public.favoritos;
drop policy if exists "favoritos_delete_anon" on public.favoritos;

create policy "favoritos_select_anon"
on public.favoritos for select
to anon
using (true);

create policy "favoritos_insert_anon"
on public.favoritos for insert
to anon
with check (true);

create policy "favoritos_delete_anon"
on public.favoritos for delete
to anon
using (true);
